server:
    port: 12345
    servlet:
        context-path: /foodApp
spring:
    data:
        mongodb:
            uri: mongodb://10.0.0.54:27017/foodApp
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: 
  secretKey: 
  bucketName: abhi-food-app